version: "3"

services:
  shopware:
    image: dockware/dev:6.5.3.0
    container_name: shopware
    ports:
      - "80:80"
      - "3306:3306"
      - "22:22"
      - "8888:8888"
      - "9999:9999"
    volumes:
      - db_volume:/var/lib/mysql
      - shop_volume:/var/www/html
    networks:
      - web
    environment:
      # default = 0, recommended to be OFF for frontend devs
      - XDEBUG_ENABLED=1
      # default = latest PHP, optional = specific version
      - PHP_VERSION=8.1

volumes:
  db_volume:
    driver: local
  shop_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: <replace-your-path>\shop_volume

networks:
  web:
    external: false
